

try{
    console.log("try block start here:");
    console.log(x);
    console.log("try block ends here:");
}

catch(e){

    console.log("I am inside catch block");
    // console.log("error: ",e);
}

finally{
console.log("I am run everytime bcz i am finally block");
}